"""empty message

Revision ID: 2ecf0357a085
Revises: None
Create Date: 2014-12-16 11:22:56.591863

"""

# revision identifiers, used by Alembic.
revision = '2ecf0357a085'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_session',
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_search_session_time_created'), 'search_session', ['time_created'], unique=False)
    op.create_table('search_query',
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('query_string')
    )
    op.create_index(op.f('ix_search_query_query_string'), 'search_query', ['query_string'], unique=False)
    op.create_table('record',
    sa.Column('record_id', sa.String(length=512), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_record_record_id'), 'record', ['record_id'], unique=False)
    op.create_table('action',
    sa.Column('record_id', sa.String(length=512), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('action_type', sa.Enum('view', 'copy', name='action_types'), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_string'], ['search_query.query_string'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.record_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['search_session.session_id'], ),
    sa.PrimaryKeyConstraint('record_id', 'session_id', 'action_type')
    )
    op.create_index(op.f('ix_action_action_type'), 'action', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_query_string'), 'action', ['query_string'], unique=False)
    op.create_index(op.f('ix_action_record_id'), 'action', ['record_id'], unique=False)
    op.create_index(op.f('ix_action_session_id'), 'action', ['session_id'], unique=False)
    op.create_index(op.f('ix_action_time_created'), 'action', ['time_created'], unique=False)
    op.create_table('imported_record_similarity',
    sa.Column('from_record_id', sa.String(length=512), nullable=False),
    sa.Column('to_record_id', sa.String(length=512), nullable=False),
    sa.Column('similarity_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_record_id'], ['record.record_id'], ),
    sa.ForeignKeyConstraint(['to_record_id'], ['record.record_id'], ),
    sa.PrimaryKeyConstraint('from_record_id', 'to_record_id')
    )
    op.create_index(op.f('ix_imported_record_similarity_from_record_id'), 'imported_record_similarity', ['from_record_id'], unique=False)
    op.create_index(op.f('ix_imported_record_similarity_to_record_id'), 'imported_record_similarity', ['to_record_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imported_record_similarity_to_record_id'), table_name='imported_record_similarity')
    op.drop_index(op.f('ix_imported_record_similarity_from_record_id'), table_name='imported_record_similarity')
    op.drop_table('imported_record_similarity')
    op.drop_index(op.f('ix_action_time_created'), table_name='action')
    op.drop_index(op.f('ix_action_session_id'), table_name='action')
    op.drop_index(op.f('ix_action_record_id'), table_name='action')
    op.drop_index(op.f('ix_action_query_string'), table_name='action')
    op.drop_index(op.f('ix_action_action_type'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_record_record_id'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_search_query_query_string'), table_name='search_query')
    op.drop_table('search_query')
    op.drop_index(op.f('ix_search_session_time_created'), table_name='search_session')
    op.drop_table('search_session')
    ### end Alembic commands ###
