"""empty message

Revision ID: a79c8de92a0
Revises: None
Create Date: 2014-11-17 11:00:52.025181

"""

# revision identifiers, used by Alembic.
revision = 'a79c8de92a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('record_id', sa.Text(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_record_record_id'), 'record', ['record_id'], unique=False)
    op.create_table('community',
    sa.Column('community_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('community_id')
    )
    op.create_index(op.f('ix_community_community_id'), 'community', ['community_id'], unique=False)
    op.create_table('search_session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_search_session_time_created'), 'search_session', ['time_created'], unique=False)
    op.create_table('search_query',
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('query_string')
    )
    op.create_table('community_query',
    sa.Column('community_id', sa.String(length=256), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.community_id'], ),
    sa.ForeignKeyConstraint(['query_string'], ['search_query.query_string'], ),
    sa.PrimaryKeyConstraint('community_id', 'query_string')
    )
    op.create_index(op.f('ix_community_query_community_id'), 'community_query', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_query_query_string'), 'community_query', ['query_string'], unique=False)
    op.create_table('result_click',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.Column('community_id', sa.String(length=256), nullable=False),
    sa.Column('record_id', sa.Text(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['query_string', 'community_id'], [u'community_query.query_string', u'community_query.community_id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.record_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['search_session.session_id'], ),
    sa.PrimaryKeyConstraint('session_id', 'query_string', 'community_id', 'record_id')
    )
    op.create_index(op.f('ix_result_click_community_id'), 'result_click', ['community_id'], unique=False)
    op.create_index(op.f('ix_result_click_query_string'), 'result_click', ['query_string'], unique=False)
    op.create_index(op.f('ix_result_click_record_id'), 'result_click', ['record_id'], unique=False)
    op.create_index(op.f('ix_result_click_session_id'), 'result_click', ['session_id'], unique=False)
    op.create_index(op.f('ix_result_click_time_created'), 'result_click', ['time_created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_click_time_created'), table_name='result_click')
    op.drop_index(op.f('ix_result_click_session_id'), table_name='result_click')
    op.drop_index(op.f('ix_result_click_record_id'), table_name='result_click')
    op.drop_index(op.f('ix_result_click_query_string'), table_name='result_click')
    op.drop_index(op.f('ix_result_click_community_id'), table_name='result_click')
    op.drop_table('result_click')
    op.drop_index(op.f('ix_community_query_query_string'), table_name='community_query')
    op.drop_index(op.f('ix_community_query_community_id'), table_name='community_query')
    op.drop_table('community_query')
    op.drop_table('search_query')
    op.drop_index(op.f('ix_search_session_time_created'), table_name='search_session')
    op.drop_table('search_session')
    op.drop_index(op.f('ix_community_community_id'), table_name='community')
    op.drop_table('community')
    op.drop_index(op.f('ix_record_record_id'), table_name='record')
    op.drop_table('record')
    ### end Alembic commands ###
